### ISSUE TITLE
Bugs e Documentação da OmniStock

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#102]
## Descrição
Arrumar pequenos erros e documentar a semana OmniStock

### Tasks: 
- [ ] Mudar link dos videos pro canal do Stock
- [ ] Arrumar path do diagrama de pacotes
- [ ] Corrigir léxico de prazo de validade
- [ ] Arrumar erros ortográficos encontrados
- [ ] Documentar vídeos e repositórios da semana de treinamento :)
