### ISSUE TITLE
Exemplificação do Padrão de Projeto

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#136]
## Descrição
Criação de modelo simples de como os padrões escolhidos podem se encaixar no contexto da aplicação.

### Tasks: 
- [x] Sofia - GRASP
- [x] Gabriel Davi - GRASP
- [x] Micaella - Factory Method
- [x] Pedro - Adapter
- [x] Gabriel Alves - State

### Critérios de aceitação

- [ ] Validar com a professora Milene ou monitor.
