### ISSUE TITLE
US02 - Login de Usuário

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#159]
## Descrição
Eu como usuário desejo realizar o login na aplicação para que eu possa ter acesso à aplicação.

### Tasks: 
- [x] Criar classe Collaborator
- [x] Salvar classe no banco
- [x] Autenticar usuário
- [x] Criar tela de login

**Comment by micaellagouveia** [comment]
Pontuação da issue:
![a1](https://user-images.githubusercontent.com/48630408/96338641-03b78700-1066-11eb-952f-8e1281d8b25b.png)
