### ISSUE TITLE
Implementação GRASP para Produtos

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#162]
## Descrição
Implementação da classe produto com suas relações com categoria e lote.

### Tasks: 
- [x] Utilizar padrões descritos em GRASP
- [x] Criação das classes Produto, Categoria e Lote 
- [x] Salvar no banco
- [x] Criação das rotas de adicionar e remover produto
- [x] Criação das rotas de adicionar e remover categoria
- [x] Relacionar produto com lote

**Comment by micaellagouveia** [comment]
Pontuação:
![produtoGRASOP](https://user-images.githubusercontent.com/48630408/96338548-47f65780-1065-11eb-9514-e1db24e6c406.png)
