### ISSUE TITLE
US01 - Cadastro da Empresa

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#176]
## Descrição
Eu como Usuário Owner desejo cadastrar minha empresa na aplicação para que eu possa criar o meu controle de estoque na aplicação

### Tasks: 
- [ ] Cadastro do Usuário Owner
- [ ] Cadastro da Empresa
- [ ] Tela de formulário

**Comment by sofiapatrocinio** [comment]
![screenshot_1](https://user-images.githubusercontent.com/38709421/97308650-dde96980-183f-11eb-8f20-9d6472156acf.png)
