### ISSUE TITLE
US07 - Cadastro de Produtos

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#188]
## Descrição
Eu como usuário Owner/Admin desejo cadastrar itens no meu controle de estoque para que eu possa administrar o fluxo do estoque

### Tasks: 
- [x] Criação da página de estoque
- [x] Adição de produtos
- [x] Adição de Lotes
