### ISSUE TITLE
Design Sprint

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#29]
## Descrição
Documentar processo de design sprint.

### Tasks: 
- [x] Explicar metodologia
- [x] Falar sobre adaptações feitas pelo time
- [x] Explicitar todas reuniões(duração, participantes, documentos individuais, mediador, dia e hora, detalhar bem para rastreabilidade)
- [x] Linkar artefatos gerados com essa documentação ("Esse artefato foi gerado por Design Sprint", algo do tipo)
- [x] Não esquecer tabela de revisão
