### ISSUE TITLE
Diagrama Causa-Efeito

### ISSUE THREAD

**Issue by gitgabiru** [UnBArqDsw/2020.1_G12_Stock#31]
### Tasks: 
- [x] Criação dos diagramas
- [x] Acrescentar hyperlinks
- [ ] Plano de ação para cada Diagrama

### Critérios de aceitação

- [x] De acordo com a documentação
- [x] Caminho dos hyperlinks corretos
- [x] Novo arquivo não gerar bugs em outros
