### ISSUE TITLE
Léxicos

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#35]
## Descrição
Produção do documento de léxicos

### Tasks: 
- [x] Receber os léxicos de todos os membros
- [ ] Criar tabela de léxicos
- [ ] Linkar todas as palavras dos documentos antigos com os léxicos criados
