### ISSUE TITLE
Documentação Reuniões e Sprints

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#42]
## Descrição
Evoluir documentos de sprints.

### Tasks: 
- [x] Adicionar relatos das reuniões
- [x] Adicionar decisões tomadas
- [x] Adicionar métricas escolhidas
