### ISSUE TITLE
Image de membros na home falha no hover e dimensão da imagem distorce no mobile

### ISSUE THREAD

**Issue by GabrielDVpereira** [UnBArqDsw/2020.1_G12_Stock#55]
## Descrição
No momento do hover da imagem, a opacidade falha. Também a imagem dos membros é distorcida quando o site é aberto no mobile. 
![image](https://user-images.githubusercontent.com/37307099/92921602-b4e55480-f40a-11ea-9e12-b9303306b322.png)

### Tasks: 
- [x] Ajustar a dimensão da imagem no mobile
- [x] ajusar o hover na imagem para não falhar quando passar o mouse no texto

### Critérios de aceitação

- [x] Dimensão da imagem normal no mobile
- [x] Imagem não falha no hover
