### ISSUE TITLE
Estimativas - Evolução

### ISSUE THREAD

**Issue by GabrielDVpereira** [UnBArqDsw/2020.1_G12_Stock#61]
## Descrição
De acordo com o feedback da monitora amanda, as estimativas de linhas poderiam ser aplicadas utilizando o desvio padrão das estimativas de linha levantada por cada integrante do grupo. 

### Tasks: 
- [x] Fazer um intervalo de estimativa utilizando o desvio padrão 
- [x] Aplicar o intervalo para o cálculo final de custo. 

### Critérios de aceitação

- [x] Cálculos revisados e corretos

**Comment by micaellagouveia** [comment]
Para esta issue a pontuação foi de:
![estimativas](https://user-images.githubusercontent.com/48630408/93001291-5c927d80-f504-11ea-9415-48f0061fd58b.png)
