### ISSUE TITLE
Questionário - Evolução

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#70]
## Descrição
Evoluir documentário de questionário

### Tasks: 
- [ ] Adicionar imagens dos resultados
- [ ] Documentar imagens com observação
- [ ] Adicionar requisitos levantados

### Critérios de aceitação

- [ ] Adição dos resultados do questionário
- [ ] Linkagem com léxicos

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![questionario](https://user-images.githubusercontent.com/48630408/93001303-73d16b00-f504-11ea-8169-e41367bbd340.png)
