### ISSUE TITLE
Entrevistas - Evolução

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#71]
## Descrição
Gravar e documentar entrevistas.

### Tasks: 
- [x] Gravar entrevista
- [x] Documentar 
- [x] Adição dos requisitos

### Critérios de aceitação

- [x] Estar documentado com áudio
- [x] Adição de requisitos listados

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![entrevistas](https://user-images.githubusercontent.com/48630408/93001312-821f8700-f504-11ea-914a-eff729d69408.png)
