### ISSUE TITLE
Protótipo de média fidelidade

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#74]
## Descrição
Elaborar protótipo de média fidelidade com base em melhorias do protótipo de baixa.

### Tasks: 
- [x] Elaborar protótipo
- [x] Testar

### Critérios de aceitação

- [x] Explicação de mudanças do de baixa pro de média
- [x] Testar com pelo menos 3 usuários
- [x] Documentar dificuldades que usuários tiveram ao usar

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![mediaFidelidade](https://user-images.githubusercontent.com/48630408/93001327-a4b1a000-f504-11ea-82d4-3a93ad6e2856.png)
