### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#75]
## Descrição
Criação do backlog de usuário.

### Tasks: 
- [x] Definir horário da reunião
- [x] Criar backlog com todas suas subdivisões.

### Critérios de aceitação

- [x] Linkagem com léxicos.

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![backlog](https://user-images.githubusercontent.com/48630408/93001339-b4c97f80-f504-11ea-9094-155067ebeaca.png)
