### ISSUE TITLE
Diagrama de Classe e Diagrama de Componentes

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#88]
## Descrição
Produção e documentação dos diagramas de classe e componentes

### Tasks: 
- [ ] Reunião com todos os membros
- [ ] Documentação dos diagramas

### Critérios de aceitação

- [ ] Estar documentado na Wiki

**Comment by micaellagouveia** [comment]
Esta issue ficou com a seguinte pontuação:
![classeComponente](https://user-images.githubusercontent.com/48630408/93670606-f90fcf00-fa72-11ea-9033-8ac217fef381.png)
