### ISSUE TITLE
Diagrama de Sequência e Diagrama de Comunicação

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#89]
## Descrição
Produção e documentação dos diagramas de sequência e comunicação

### Tasks: 
- [x] Reunião com todos os membros
- [x] Documentação dos diagramas

### Critérios de aceitação

- [x] Estar documentado na Wiki

**Comment by micaellagouveia** [comment]
Esta issue ficou com a seguinte pontuação:
![sequenciaCOmunicacao](https://user-images.githubusercontent.com/48630408/93670654-602d8380-fa73-11ea-8a92-f9003ea958a4.png)
