### ISSUE TITLE
Diagrama de Atividades e Diagrama de Estado

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#90]
## Descrição
Produção e documentação dos diagramas de atividades e estado

### Tasks: 
- [x] Reunião com todos os membros
- [x] Documentação dos diagramas

### Critérios de aceitação

- [x] Estar documentado na Wiki

**Comment by micaellagouveia** [comment]
Esta issue ficou com a seguinte pontuação:
![atividadesEstado](https://user-images.githubusercontent.com/48630408/93670709-c1eded80-fa73-11ea-9956-d20c01d412cf.png)
