### ISSUE TITLE
Diagrama de Pacotes e Entidade Relacionamento de Banco de Dados

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#91]
## Descrição
Produção e documentação dos diagramas de pacote e entidade relacionamento de banco de dados

### Tasks: 
- [ ] Reunião com todos os membros
- [ ] Documentação dos diagramas

### Critérios de aceitação

- [ ] Estar documentado na Wiki

**Comment by micaellagouveia** [comment]
Esta issue ficou com a seguinte pontuação:
![bancoPacotes](https://user-images.githubusercontent.com/48630408/93670754-12654b00-fa74-11ea-824d-bbedbcd1007d.png)
