### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#94]
## Descrição
Produção do protótipo de alta fidelidade

### Tasks: 
- [x] Elencar soluções retiradas do protótipo de média fidelidade
- [x] Produzir protótipo de alta fidelidade

### Critérios de aceitação

- [x] Estar documentado na Wiki

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a seguinte pontuação:
![altaFidelidade](https://user-images.githubusercontent.com/48630408/93670964-85bb8c80-fa75-11ea-8903-350385c65725.png)
